{{- if .Values.conditionalPackageInstalls.certManager }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: migration-ca-issuer
  labels:
    app: {{ .Release.Name }}
spec:
  ca:
    secretName: migration-ca-key-pair
{{- end }}
