{{- if .Values.conditionalPackageInstalls.certManager }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: migration-ca-test
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  duration: 1h  # Short duration since it's just a test
  renewBefore: 30m
  secretName: migration-ca-test
  commonName: "migration-ca-test.{{ .Release.Namespace }}.svc"
  dnsNames:
    - "migration-ca-test.{{ .Release.Namespace }}.svc"
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
{{- end }}
