parameters:
  destinationUri:
    source: parameterConfig
    value: "http://sourcecluster.example.com:9200"
    allowRuntimeOverride: false
  listenPort:
    source: parameterConfig
    value: 9200
    allowRuntimeOverride: false
#  noCapture:
#    source: parameterConfig
#    parameterType: booleanFlag
#    value: false
#    allowRuntimeOverride: true
  insecureDestination:
    source: parameterConfig
    parameterType: booleanFlag
    value: true
    allowRuntimeOverride: false
  # Kafka SSL Configuration
  kafkaSslEnabled:
    source: otherConfig
    configMapName: "kafka-brokers"
    configMapKey: "sslEnabled"
    parameterType: booleanFlag
    allowRuntimeOverride: false
  kafkaSecurityProtocol:
    source: otherConfig
    configMapName: "kafka-brokers"
    configMapKey: "securityProtocol"
    allowRuntimeOverride: false
  kafkaSslTruststoreLocation:
    source: otherConfig
    configMapName: "kafka-brokers"
    configMapKey: "sslTruststoreLocation"
    allowRuntimeOverride: false
  kafkaSslKeystoreLocation:
    source: otherConfig
    configMapName: "kafka-brokers"
    configMapKey: "sslKeystoreLocation"
    allowRuntimeOverride: false
  kafkaSslKeystorePassword:
    source: otherConfig
    configMapName: "kafka-brokers"
    configMapKey: "sslKeystorePassword"
    allowRuntimeOverride: false
# TODO - setup cert management
#  sslConfigFile:
#    source: parameterConfig
#    value: "/usr/share/elasticsearch/config/proxy_tls.yml"
#    allowRuntimeOverride: false
#  otelCollectorEndpoint:
#    source: parameterConfig
#    value: "http://otel-collector:4317"
#    allowRuntimeOverride: false
